const CAKE_ORDERED = 'CAKE_ORDERED';

const CAKE_RESTOCKED = 'CAKE_RESTOCKED';

const ICECREAM_ORDERED = 'ICECREAM_ORDERED';

const ICECREAM_RESTOCKED = 'ICECREAM_RESTOCKED';

module.exports = {
    CAKE_ORDERED,
    CAKE_RESTOCKED,
    ICECREAM_ORDERED,
    ICECREAM_RESTOCKED
};